service: reconciliation-engine-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'ap-south-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_ENV: ${self:provider.stage}
  deploymentBucket:
    # Use a custom prefix to satisfy the IAM least privilege policy "arn:aws:s3:::reconciliation-engine-*"
    name: reconciliation-engine-deployments-${sls:instanceId}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: '*'
